version: "3.7"

services:
    nginx-proxy:
        image: nginx:1.19.6
        container_name: nginx-proxy
        hostname: nginx-proxy
        volumes:
            - ./conf.d/nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        restart: always
        command: >
            /bin/bash -c "
                envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf \
                && exec nginx -g 'daemon off;'
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.2

    postgres:
        image: postgres:latest
        container_name: localdb
        hostname: postgres
        environment:
            - POSTGRES_DB=localdb
            - POSTGRES_USER=localdb
            - POSTGRES_PASSWORD=localdb
        networks:
            mynet: 
                ipv4_address: 172.28.0.3

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"

volumes:
    webroot:
        name: webroot
    postgres:
        name: postgres
