server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:54321/localdb
    username: localdb
    password: localdb

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: postgresql